---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.12
  commands:
  - go test -v ./...
  - sh scripts/build.sh

- name: publish_amd64
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: drone/vault
  when:
    event:
    - push
    - tag

- image: plugins/docker:18
  name: publish_arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: drone/vault
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: publish_arm
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: docker/Dockerfile.linux.arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: drone/vault
  when:
    event:
    - push
    - tag

- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag