---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/drone/drone-vault

steps:
- name: build
  image: golang:1.10
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test -v -cover ./...
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-vault github.com/drone/drone-vault/cmd/drone-vault

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile
    password:
      $secret: docker_password
    repo: drone/vault
    username:
      $secret: docker_username

---
kind: secret
type: external
data:
  docker_password: "drone/docker#password"
  docker_username: "drone/docker#username"

...
