FROM alpine:3.17 as alpine
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.17
EXPOSE 3000

ENV GODEBUG netdns=go

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD release/linux/arm/drone-vault /bin/
ENTRYPOINT ["/bin/drone-vault"]