FROM alpine:3.9

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Vault Secrets" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000
ENV GODEBUG netdns=go

RUN apk add --no-cache ca-certificates

ADD release/linux/amd64/drone-vault-secrets /bin/
ENTRYPOINT ["/bin/drone-vault-secrets"]
